sudo: false
language: Java
jdk:
  - oraclejdk8
install: mvn -q clean -DskipTests -DskipITs install
script: mvn -Dtest=org.kaazing.gateway.management.jmx.JmxManagementServiceHandlerTest test -DfailIfNoTests=false
