sudo: false
language: Java
jdk:
  - oraclejdk8
install: mvn -q clean -DskipTests -DskipITs install
script: mvn -f ./management/pom.xml -Dtest=JmxManagementServiceHandlerTest test && mvn cobertura:cobertura-integration-test coveralls:report
