sudo: required
language: Java
jdk: oraclejdk8
env:
  global:
    - secure: "sG5h/UB/s3uhN6DF4F4jRHLKDTbqGipDdCBaUu/8mZ8kqgtZtMAh6yodj1HrRbEzov0kCsjDYTnv90YzZWIbmrzRNY3M/B/P47DKkCxjf6ejbSY9D0OJnqbjzOyfiDP6bAs64pUzfjylkYuvNVhkCxN0Ay7k8cvT9D0XOX3nUHc="
    - secure: "P5oMhssZHp8eBezF2WEUZrzR6du/ibhcNRmZhSC8uKN0NO6AKlGLBID2llQrWED7RoZLoYhReR04LqdQZboGKvmqZ1TRHDkhwUOsFAGFIC2wxFrZPNy06anOjaT+ZfOsMZCtN+mXCaCARSBCSJP7L0vyEIdfaw+ZG2LxBV2GrK0="
before_install: certificates/add-to-cacerts.sh
install: mvn -q clean -DskipTests -DskipITs install
script: mvn verify -X -f ./transport/nio/pom.xml
